name: CI/CD with Maven, DockerHub and Docker in Remote Server
on:
  workflow_dispatch:
  workflow_call:
    secrets:
        DOCKERHUB_USERNAME:
          required: true
        DOCKERHUB_TOKEN:
          required: true
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Code Checkout
      uses: actions/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        context: .
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-docker:latest

    - name: Deploy Application using SSH
      uses: cross-the-world/ssh-scp-ssh-pipelines@latest
      env:
        WELCOME: "ssh scp ssh pipelines"
        LASTSSH: "Doing something after copying"
      with:
        host: 'fotioskoutsoukosl0034.simplilearnlabs.com'
        user: 'fotioskoutsouko'
        pass: 'tsouko0A@3ykwy'
        port: 42006
        connect_timeout: 10s
        first_ssh: |
          rm -rf /tmp/Docker
          mkdir -p /tmp/Docker
        scp: |
          'Dockerfile' => /tmp/Docker
        last_ssh: |
          docker run -d  -P ${{ secrets.DOCKERHUB_USERNAME }}/spring-boot-docker:latest

