name: Caller

on:
  push:
    branches: [ "master" ]

jobs:
  Reusable-caller-job:
    uses: ./.github/workflows/basic-workflow.yaml
    secrets:
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
